# Generated by Django 4.0 on 2024-01-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemash_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmoviedata',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
