# Generated by Django 4.0 on 2024-01-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemash_core', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmoviedata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
